// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using RHS.Infrastructure.Data;

#nullable disable

namespace RHS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530_AddStaffRoles")]
    partial class AddStaffRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Model configuration would go here if needed
#pragma warning restore 612, 618
        }
    }
}
